(require 'jedi)
(require 'sphinx-doc)
(eval-after-load 'company '(push 'company-jedi company-backends))
(defun my/python-hook ()
  (sphinx-doc-mode t))
(add-hook 'python-mode-hook 'my/python-hook)
(add-hook 'python-mode-hook 'jedi:setup)
(add-to-list 'interpreter-mode-alist '("python2" . python-mode))
(add-to-list 'interpreter-mode-alist '("python3" . python-mode))
(provide 'python)
